# Generated by Django 3.2.13 on 2022-10-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
